import { describe, expect, it } from 'vitest';

import { contentHash } from '../shared/primitives.js';
import { ECOMMERCE_SYSTEM, TICKET_BOOKING_SYSTEM, COLLAB_DOCS_SYSTEM } from './flagships.js';
import { MVP_CACHE_SYSTEM } from './mvp-cache.js';
import { runSystemScript } from './runtime.js';

/**
 * Committed composite golden vectors. Changing runtime semantics requires
 * intentionally updating these hashes (treat diffs like snapshot updates).
 */
const VECTORS: Array<{ key: string; run: () => { contentHash: string }; sha: string }> = [
  {
    key: 'mvp-cache.cache-hit.seed42',
    run: () => runSystemScript(MVP_CACHE_SYSTEM, { seed: 42, events: MVP_CACHE_SYSTEM.scenarios.find((s) => s.id === 'cache-hit')!.events }),
    sha: '',
  },
  {
    key: 'mvp-cache.cache-miss.seed42',
    run: () => runSystemScript(MVP_CACHE_SYSTEM, { seed: 42, events: MVP_CACHE_SYSTEM.scenarios.find((s) => s.id === 'cache-miss')!.events }),
    sha: '',
  },
  {
    key: 'ecommerce.checkout.seed42',
    run: () => runSystemScript(ECOMMERCE_SYSTEM, { seed: 42, events: ECOMMERCE_SYSTEM.scenarios.find((s) => s.id === 'checkout')!.events }),
    sha: '',
  },
  {
    key: 'ticket-booking.race.seed42',
    run: () => runSystemScript(TICKET_BOOKING_SYSTEM, { seed: 42, events: TICKET_BOOKING_SYSTEM.scenarios.find((s) => s.id === 'double-race')!.events }),
    sha: '',
  },
  {
    key: 'collab-docs.concurrent-edit.seed42',
    run: () => runSystemScript(COLLAB_DOCS_SYSTEM, { seed: 42, events: COLLAB_DOCS_SYSTEM.scenarios.find((s) => s.id === 'concurrent-edit')!.events }),
    sha: '',
  },
];

function compute(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const v of VECTORS) out[v.key] = v.run().contentHash;
  return out;
}

// Committed hashes — generated by running compute() once and pasting below.
const COMMITTED: Record<string, string> = {
  'mvp-cache.cache-hit.seed42': '98c8bf38',
  'mvp-cache.cache-miss.seed42': 'b28aeaeb',
  'ecommerce.checkout.seed42': '51f765d1',
  'ticket-booking.race.seed42': 'ff21a0f6',
  'collab-docs.concurrent-edit.seed42': 'e76d1d3a',
};

describe('composite golden vectors', () => {
  it('prints current hashes for (re)generation', () => {
    const current = compute();
    // Always passes; output is the source for COMMITTED updates.
    // eslint-disable-next-line no-console
    console.log(`COMPOSITE_GOLDENS ${contentHash(current)} ${JSON.stringify(current)}`);
    for (const v of VECTORS) {
      const expected = COMMITTED[v.key];
      if (expected !== '__REGEN__') expect(current[v.key]).toBe(expected);
    }
    expect(Object.keys(current)).toHaveLength(VECTORS.length);
  });
});
