import type { Challenge } from '@the-visualizer/contracts';

/**
 * Hand-authored challenge set: one "find the flaw" challenge per domain, each
 * tied to a real invariant ID (verified against the domain's checker) and,
 * where a named chaos scenario exists, to that scenario.
 */
export const CHALLENGE_BANK: Challenge[] = [
  {
    id: 'kafka-ch1',
    domainId: 'kafka',
    title: 'Lose an acknowledged write',
    invariantId: 'HIGH_WATERMARK_BOUND',
    brief: 'A producer with acks=1 writes steadily while you crash leaders. Find a committed-by-the-client write that never survives failover.',
    chaosScenarioId: 'kafka-broker-crash',
    hints: ['Watch which broker leads the partition you write to.', 'acks=1 only waits for the leader. What has the leader told the followers?', 'Crash the leader before replication catches up.'],
    explanation: 'With acks=1 the write is "committed" once the leader appends it. If the leader dies before followers replicate, the new leader never saw it — the client was told success for data that no longer exists.',
    mitigation: 'acks=-1 with min.insync.replicas=2: the write is acknowledged only after ISR replication, trading availability for durability.',
  },
  {
    id: 'raft-ch1',
    domainId: 'raft',
    title: 'Force a leaderless term',
    invariantId: 'RAFT_LEADER',
    brief: 'Trigger an election where nobody wins. The cluster must sit leaderless for a full term.',
    chaosScenarioId: 'raft-election-race',
    hints: ['You need two candidates, not one.', 'Partition the voters so each candidate gets exactly half.', 'Watch the term increment with no leader elected.'],
    explanation: 'Split votes (2-2-1 in a 5-node cluster) elect nobody. Both candidates time out, the term increments, and randomized timeouts make a repeat unlikely — but the leaderless window is real.',
    mitigation: 'Randomized election timeouts plus pre-vote: candidates that cannot win disrupt less, and single-voter partitions cannot force elections.',
  },
  {
    id: 'database-ch1',
    domainId: 'database',
    title: 'Read your own stale write',
    invariantId: 'DB-2',
    brief: 'With W=1, write a value and immediately read it back from a different replica. Observe staleness.',
    chaosScenarioId: 'db-quorum-race',
    hints: ['Lower the write quorum to 1.', 'Read from a replica that was not in the write set.', 'Compare with R+W>N configured.'],
    explanation: 'W=1, R=1 quorums need not overlap, so a read can miss the latest write entirely. The scenario makes the R+W>N overlap requirement visceral.',
    mitigation: 'Choose quorums with R+W>N, or accept eventual consistency explicitly and add read-repair.',
  },
  {
    id: 'redis-ch1',
    domainId: 'redis',
    title: 'Serve stale data after failover',
    invariantId: 'REDIS_STALENESS',
    brief: 'Write heavily, then fail over to a lagging replica. Serve reads the old master already answered differently.',
    chaosScenarioId: 'redis-master-failover',
    hints: ['Async replication is the gap — find the lag metric.', 'Fail over mid-write-burst, not at idle.', 'Compare a key read before and after promotion.'],
    explanation: 'The replica lags by the replication offset delta; promotion freezes that lag into served state. Anything written after the replica’s last applied offset is silently lost to readers.',
    mitigation: 'WAIT for replica acknowledgement on critical writes, or accept bounded staleness and document it in the SLA.',
  },
  {
    id: 'kubernetes-ch1',
    domainId: 'kubernetes',
    title: 'Starve a pod forever',
    invariantId: 'K8S_CPU_OVERCOMMIT',
    brief: 'Craft a pod whose honest resource requests fit no node. It must sit Pending indefinitely.',
    chaosScenarioId: 'k8s-pod-pending-starvation',
    hints: ['Request more than the largest allocatable node offers.', 'Watch the scheduler’s fit predicate reject every node.', 'Now try with limits but no requests — what changes?'],
    explanation: 'The scheduler only matches requests against allocatable capacity. An unsatisfiable request is never "retried into success" — Pending is terminal until the pod spec or the fleet changes.',
    mitigation: 'Right-size requests, add node autoscaling or larger instance types, and alert on long-Pending pods.',
  },
  {
    id: 'rabbitmq-ch1',
    domainId: 'rabbitmq',
    title: 'Poison the queue',
    invariantId: 'RABBIT_DLQ',
    brief: 'Publish one malformed message that a consumer always rejects. Block the entire queue behind it.',
    chaosScenarioId: 'rabbit-dlx-poison-pill',
    hints: ['Reject without requeue=false redelivers forever.', 'Watch the redelivery counter climb on one message.', 'Head-of-line blocking: what happens to messages behind it?'],
    explanation: 'A single poison message redelivered infinitely head-of-line-blocks all consumers. Without a dead-letter policy, one bad payload is a full queue outage.',
    mitigation: 'Max-redelivery-count → dead-letter exchange with alerts; quarantine and inspect DLQ contents.',
  },
  {
    id: 'storage-ch1',
    domainId: 'storage',
    title: 'Stall writes with compaction debt',
    invariantId: 'LSM_STALL',
    brief: 'Outrun compaction with sustained writes until L0 fills and the engine stalls incoming writes.',
    chaosScenarioId: 'storage-lsm-compaction',
    hints: ['Writes are fast; compaction is the bottleneck.', 'Sustain write throughput above the compaction drain rate.', 'Watch pending SSTables accumulate, then the stall.'],
    explanation: 'LSM write amplification is deferred work. When L0 file count crosses the stall threshold, the engine must throttle or block writes to let compaction catch up — throughput falls off a cliff.',
    mitigation: 'Size-tiered leveling strategy, compaction concurrency, write throttling with backpressure instead of hard stalls.',
  },
  {
    id: 'networking-ch1',
    domainId: 'networking',
    title: 'Collapse throughput with loss',
    invariantId: 'NET-3',
    brief: 'Introduce sustained packet loss and watch AIMD drive the congestion window to a fraction of link capacity.',
    chaosScenarioId: 'tcp-congestion-aimd',
    hints: ['Each loss halves cwnd (Reno) — compound that.', 'Additive increase recovers slowly; multiplicative decrease is instant.', 'Compare achieved throughput to the loss-free baseline.'],
    explanation: 'AIMD converges to fairness, not to full utilization under loss: persistent random loss keeps halving the window faster than linear growth recovers it. This is why loss-based control underperforms on lossy links.',
    mitigation: 'BBR-style model-based control, selective acknowledgements, or fixing the underlying loss (bufferbloat, policers).',
  },
  {
    id: 'rate-limiter-ch1',
    domainId: 'rate-limiter',
    title: 'Double the allowed rate for free',
    invariantId: 'RL-3',
    brief: 'Using Fixed Window, admit nearly 2× the configured limit by bursting across a window boundary.',
    hints: ['Spend the full quota at 11:59:59.', 'Spend it again at 12:00:00.', 'Check the admitted total against the limit.'],
    explanation: 'Fixed Window resets blindly at boundaries, so two adjacent bursts each consume a full quota. The enforced rate is double the advertised one precisely when traffic spikes.',
    mitigation: 'Sliding Window Log (exact), Sliding Window Counter, or Token Bucket — all bound the trailing-window total.',
  },
  {
    id: 'distributed-lock-ch1',
    domainId: 'distributed-lock',
    title: 'Break mutual exclusion without killing any node',
    invariantId: 'LOCK-4',
    brief: 'Pause a lock holder past its TTL (GC pause / STW) while a second client acquires the same lock. Two holders, one lock.',
    hints: ['The holder is alive but stalled — not crashed.', 'TTL expiry is time-based, not liveness-based.', 'Watch LOCK-4 fire when both holders act.'],
    explanation: 'Time-based locks cannot distinguish "crashed" from "paused". The Kleppmann scenario shows mutual exclusion violated with all nodes healthy — the flaw is structural to naive Redlock.',
    mitigation: 'Fencing tokens: every grant carries a monotonic token and storage rejects stale-token writes.',
  },
  {
    id: 'cdn-cache-ch1',
    domainId: 'cdn-cache',
    title: 'Stampede the origin',
    invariantId: 'CDN-3',
    brief: 'Expire a hot key and fire hundreds of concurrent requests so every one misses and hits origin simultaneously.',
    hints: ['Pick the hottest key in the working set.', 'Expire it, then burst — not gradually.', 'Watch origin concurrency spike 100×.'],
    explanation: 'Concurrent misses on one hot key multiply into an origin flood — the thundering herd. CDN-3 fires on the origin-concurrency collapse.',
    mitigation: 'Request coalescing (single-flight), probabilistic early refresh, stale-while-revalidate.',
  },
  {
    id: 'id-gen-ch1',
    domainId: 'id-gen',
    title: 'Duplicate an ID with clock skew',
    invariantId: 'ID-3',
    brief: 'Drive the generator clock backward past issued timestamps and observe ID-3 fire — or duplicate IDs if refusal is disabled.',
    hints: ['NTP corrections move clocks backward, not just forward.', 'Same millisecond + same sequence = same ID.', 'What should the generator do instead of emitting?'],
    explanation: 'Snowflake IDs embed time; backward time reuses ID space. Emitting anyway duplicates primary keys. ID-3 enforces refusal — the only safe answer.',
    mitigation: 'Refuse-and-alert on backward skew beyond tolerance; monitor NTP offset as a first-class health signal.',
  },
  {
    id: 'transactions-ch1',
    domainId: 'transactions',
    title: 'Hang a transaction forever',
    invariantId: 'TXN-2',
    brief: 'Crash the 2PC coordinator after PREPARE but before the decision. Participants must block holding locks.',
    hints: ['Vote YES first — then the coordinator dies.', 'A YES-voter cannot unilaterally abort (someone else may commit).', 'Watch locks held with zero progress.'],
    explanation: 'The 2PC blocking hazard: uncertain participants hold locks indefinitely. This window is why 2PC is unsuitable when coordinator availability cannot be guaranteed.',
    mitigation: '3PC with timeouts, Paxos-commit, or saga orchestration that avoids cross-service locks.',
  },
  {
    id: 'rag-ch1',
    domainId: 'rag',
    title: 'Bury the answer with chunking',
    invariantId: 'RAG-1',
    brief: 'Widen chunk size until a query whose answer exists in the corpus stops being retrieved.',
    hints: ['The text is indexed — recall still drops. Why?', 'Embeddings average their chunk; dilution kills similarity.', 'Compare recall at 300 vs 4000 tokens.'],
    explanation: 'Coarse chunks dilute the relevant passage’s signal below retrieval threshold. The corpus contains the answer and the system still fails — a chunking bug, not a model bug.',
    mitigation: 'Tight overlapping chunks, hierarchical retrieval, hybrid dense+BM25 with RRF.',
  },
  {
    id: 'agents-ch1',
    domainId: 'agents',
    title: 'Loop the agent forever',
    invariantId: 'AGENT-1',
    brief: 'Give the agent an unachievable subgoal with a failing tool. Watch it retry identically until the budget dies.',
    hints: ['Same arguments, same failure, no progress — spot the loop.', 'What would a human do after the third identical failure?', 'Check AGENT-1’s progress detector.'],
    explanation: 'Without progress-gated termination, plan-act loops burn budget forever. AGENT-1 fires when iterations accumulate with no state progress.',
    mitigation: 'Step budgets, progress detection, plan revision triggers, and human-in-the-loop escalation.',
  },
  {
    id: 'llm-serving-ch1',
    domainId: 'llm-serving',
    title: 'Waste VRAM with fragmentation',
    invariantId: 'LLM-1',
    brief: 'Schedule adversarial sequence mixes until internal KV-cache fragmentation breaches budget.',
    hints: ['Contiguous reservation wastes every sequence tail.', 'Mix very long and very short sequences.', 'Watch allocated-vs-used diverge.'],
    explanation: 'Static contiguous allocation strands memory in unusable tails. LLM-1 fires when waste crosses budget — the inefficiency PagedAttention was built to kill.',
    mitigation: 'Paged KV-cache blocks, right-sized block allocation, defragmenting schedulers.',
  },
  {
    id: 'vectordb-ch1',
    domainId: 'vectordb',
    title: 'Tank recall with a bad entry point',
    invariantId: 'VEC-1',
    brief: 'Degrade HNSW entry-point quality and watch greedy routing converge to the wrong neighborhood.',
    hints: ['HNSW never backtracks across layers.', 'A bad entry descends into the wrong basin.', 'Raise efSearch — does it fully recover?'],
    explanation: 'No backtracking means entry quality bounds recall. VEC-1 fires when routing quality collapses; wider efSearch mitigates but cannot fix a broken entry.',
    mitigation: 'Quality entry selection, adequate efConstruction at build, recall monitoring in production.',
  },
  {
    id: 'gpu-cluster-ch1',
    domainId: 'gpu-cluster',
    title: 'Maximize the pipeline bubble',
    invariantId: 'GPU-1',
    brief: 'Configure few micro-batches across many stages so fill/drain idle dominates the schedule.',
    hints: ['Bubble ∝ (stages−1)/(micro-batches).', 'Push stages up, micro-batches down.', 'Read the bubble fraction off GPU-1.'],
    explanation: 'Pipeline parallelism taxes every schedule with fill/drain idle. Starved of micro-batches, GPUs sit idle most of the step — the fundamental 1F1B tradeoff made visible.',
    mitigation: 'More micro-batches, interleaved 1F1B schedules, or fewer stages.',
  },
  {
    id: 'llm-pipeline-ch1',
    domainId: 'llm-pipeline',
    title: 'Overflow the token budget silently',
    invariantId: 'PIPE-1',
    brief: 'Push one stage past its token budget and watch downstream quality degrade with no error raised.',
    hints: ['Truncation without signal is the enemy.', 'Which stage drops content first?', 'Check what the final answer lost.'],
    explanation: 'Unaccounted overflow silently truncates context. PIPE-1 fires on budget violation so truncation becomes explicit and attributable instead of mysterious quality rot.',
    mitigation: 'Per-stage budget accounting, explicit truncation signals, U-shaped budget windows.',
  },
  {
    id: 'llm-gateway-ch1',
    domainId: 'llm-gateway',
    title: 'Bankrupt a tenant with one client',
    invariantId: 'GW-1',
    brief: 'Run one tenant hot with no budget cap until shared p99 collapses or cost guardrails fire.',
    hints: ['Noisy neighbors spend shared capacity.', 'Watch other tenants’ latency, not just yours.', 'Where should admission have stopped you?'],
    explanation: 'Without per-tenant budgets, one runaway client starves or bankrupts everyone. GW-1 enforces admission against live counters — the challenge is reaching the fire first.',
    mitigation: 'Per-tenant token budgets, priority lanes, load shedding with Retry-After.',
  },
  {
    id: 'load-balancer-ch1',
    domainId: 'load-balancer',
    title: 'Route into a dead backend',
    invariantId: 'LB-1',
    brief: 'Desync the data plane from health state so traffic flows to a backend marked unhealthy.',
    hints: ['Push a stale config, or point the checker at the wrong port.', 'Compare the active set against the healthy set.', 'LB-1 fires on exactly this divergence.'],
    explanation: 'Health checks are advisory unless the data plane honors them. LB-1 catches the control-plane/data-plane split — the signature of stale pushes and miswired checkers.',
    mitigation: 'Atomic config rollout, checker self-validation, active-set reconciliation loops.',
  },
  {
    id: 'search-index-ch1',
    domainId: 'search-index',
    title: 'Spam your way to rank one',
    invariantId: 'SEARCH-1',
    brief: 'Stuff a document with a query term until linear TF would crown it — and watch saturation refuse.',
    hints: ['Repeat the term 100×. What happens to the score curve?', 'Saturation (k1) flattens the payoff — find the knee.', 'Disable saturation mentally: who wins then?'],
    explanation: 'BM25’s saturating TF curve is the anti-spam core. SEARCH-1 verifies the bound holds — keyword stuffing buys ever-less rank, exactly as designed.',
    mitigation: 'Keep k1 calibrated; monitor for injection-style stuffing at index time.',
  },
  {
    id: 'task-scheduler-ch1',
    domainId: 'task-scheduler',
    title: 'Run a task before its dependency',
    invariantId: 'SCHED-1',
    brief: 'Force an edge-order violation so downstream consumes missing inputs — a phantom success.',
    hints: ['Retry storms re-queue tasks mid-dependency.', 'Watch a task go green on absent inputs.', 'The output looks fine. It is not.'],
    explanation: 'Topological order is the DAG contract. SCHED-1 fires on edge violations — the phantom success (green task, garbage inputs) is the most dangerous scheduler failure mode.',
    mitigation: 'Dependency-aware requeueing, input-existence gates, lineage checks.',
  },
  {
    id: 'chat-presence-ch1',
    domainId: 'chat-presence',
    title: 'Reorder causality with clocks',
    invariantId: 'CHAT-1',
    brief: 'Skew two writers’ clocks so a reply renders before the message it answers.',
    hints: ['Wall-clock timestamps are the vulnerability.', 'Skew writer B +2s ahead of writer A.', 'Causal order needs sequences, not clocks.'],
    explanation: 'Client clocks disagree, so timestamp order is not causal order. CHAT-1 enforces server-assigned per-room sequences — the only order every client shares.',
    mitigation: 'Server-side sequencing; vector clocks for peer-to-peer variants.',
  },
  {
    id: 'feature-store-ch1',
    domainId: 'feature-store',
    title: 'Train on the future',
    invariantId: 'FS-1',
    brief: 'Leak post-label feature values into training via a sloppy as-of join. Watch offline metrics soar and production collapse.',
    hints: ['Join "current" features instead of as-of.', 'The model learns what production will never know.', 'Compare offline vs online feature values.'],
    explanation: 'Training-serving skew from future leakage is the silent killer: great offline, broken live. FS-1 enforces point-in-time correctness on every join.',
    mitigation: 'As-of joins with event-time semantics, PIT validation gates, training/serving parity checks.',
  },
  {
    id: 'model-rollout-ch1',
    domainId: 'model-rollout',
    title: 'Promote a silently regressing model',
    invariantId: 'ROLL-1',
    brief: 'Find a canary whose aggregate error rate holds flat while one cohort burns — then block (or allow) its promotion.',
    hints: ['Slice the metrics, not just the mean.', 'One cohort regressing + others improving = flat aggregate.', 'Would you promote on the headline number?'],
    explanation: 'Simpson’s paradox in production gates. ROLL-1 requires slice-aware guardrails — the challenge is catching what the aggregate hides.',
    mitigation: 'Per-slice promotion gates, automated holdbacks, cohort-level alerting.',
  },
  {
    id: 'llm-eval-ch1',
    domainId: 'llm-eval',
    title: 'Pass eval by memorization',
    invariantId: 'EVAL-1',
    brief: 'Contaminate training with eval items and watch scores inflate while true capability stands still.',
    hints: ['Near-duplicates count as contamination too.', 'Compare held-out-fresh vs benchmark scores.', 'The gap is the memorization premium.'],
    explanation: 'Contaminated evals certify broken models. EVAL-1 enforces hash-verified train/eval isolation — the challenge demonstrates why gates without it are theater.',
    mitigation: 'Canary strings, decontamination pipelines, fresh held-out evals per release.',
  },
  {
    id: 'consistent-hashing-ch1',
    domainId: 'consistent-hashing',
    title: 'Hot-spot the ring',
    invariantId: 'CHASH-2',
    brief: 'With few virtual nodes, drive the imbalance ratio until one node owns a wildly disproportionate range.',
    hints: ['Random placement is lumpy with few samples.', 'Measure max/min owned range.', 'Add vnodes and watch convergence.'],
    explanation: 'Without vnodes, random ring placement routinely deals 2× load to unlucky nodes. CHASH-2 quantifies the imbalance — the challenge makes the statistics tangible.',
    mitigation: 'High vnode counts, bounded-loads consistent hashing, imbalance alerting.',
  },
  {
    id: 'probabilistic-structures-ch1',
    domainId: 'probabilistic-structures',
    title: 'Drown the filter past design capacity',
    invariantId: 'PROB-2',
    brief: 'Insert 10× the design elements and measure the false-positive rate collapse from 1% toward coin-flip.',
    hints: ['FPR degrades as occupancy exceeds design.', 'Measure empirically, compare with theory.', 'At what fill does it become useless?'],
    explanation: 'An overfilled Bloom filter still answers — just wrongly, half the time. PROB-2 tracks measured-vs-theory FPR; the challenge shows silent degradation in action.',
    mitigation: 'Capacity planning, scalable Bloom filters, FPR monitoring with rebuild triggers.',
  },
  {
    id: 'merkle-trees-ch1',
    domainId: 'merkle-trees',
    title: 'Find the divergent leaf with minimal hashing',
    invariantId: 'MERKLE-1',
    brief: 'Given two roots that disagree, descend proof paths to isolate the divergent leaves without comparing full datasets.',
    hints: ['Compare children, descend only into disagreement.', 'Each level halves the search space.', 'Count hashes used vs full comparison.'],
    explanation: 'Anti-entropy in logarithmic work: the root tells you something differs, proof descent tells you what, touching only O(log n) hashes per divergent leaf.',
    mitigation: 'Merkle-driven replica sync, proof-cached verification, subtree versioning.',
  },
];

export function challengeForDomain(domainId: string): Challenge[] {
  return CHALLENGE_BANK.filter((c) => c.domainId === domainId);
}

export function challengeById(id: string): Challenge | undefined {
  return CHALLENGE_BANK.find((c) => c.id === id);
}
