import type { InterviewScript } from '@the-visualizer/contracts';

/** Hand-authored interview walkthroughs. Self-assessed via rubric checklists — no grading model. */
export const INTERVIEW_SCRIPTS: InterviewScript[] = [
  {
    id: 'design-rate-limiter',
    title: 'Design a Rate Limiter',
    question: 'Design a rate limiter for a public API handling 100k requests/second across 3 regions.',
    topicTags: ['system-design', 'algorithms', 'backend'],
    timeLimitMinutes: 35,
    steps: [
      {
        stepId: 'rl-pick',
        title: 'Choose an algorithm',
        domainId: 'rate-limiter',
        instruction: 'Open /rate-limiter and compare Fixed Window, Sliding Window Log, Sliding Window Counter, and Token Bucket. Pick one and state why.',
        hint: 'Start by disqualifying one algorithm with a concrete flaw, not by praising your favorite.',
        rubricItem: 'Names a concrete algorithm and justifies it against at least one alternative with a specific flaw.',
      },
      {
        stepId: 'rl-boundary',
        title: 'Trigger the boundary burst',
        domainId: 'rate-limiter',
        instruction: 'Run the Fixed Window boundary-burst chaos scenario and explain why the 2× burst is disqualifying at 100k rps.',
        hint: 'Two full quotas back-to-back at a window edge. Multiply by your traffic.',
        rubricItem: 'Explains the boundary-burst mechanism and quantifies its impact at scale.',
      },
      {
        stepId: 'rl-distributed',
        title: 'Go multi-region',
        domainId: 'rate-limiter',
        instruction: 'Explain where limiter state lives with 3 regions: sticky routing, centralized Redis, or local approximation with reconciliation?',
        hint: 'Cross-region coordination latency kills exactness — what approximation do you accept?',
        rubricItem: 'Addresses distributed state with an explicit consistency/cost tradeoff.',
      },
    ],
  },
  {
    id: 'raft-leader-election',
    title: 'Raft Leader Election Under Partition',
    question: 'Walk through leader election in a 5-node Raft cluster during a network partition.',
    topicTags: ['consensus', 'backend'],
    timeLimitMinutes: 30,
    steps: [
      {
        stepId: 'raft-race',
        title: 'Run the election race',
        domainId: 'raft',
        instruction: 'Open /raft and run the raft-election-race scenario. Explain why split votes force a new term.',
        hint: 'Count votes: who needs what, and what happens at 2-2-1?',
        rubricItem: 'Explains split votes, randomized timeouts, and term increments.',
      },
      {
        stepId: 'raft-split',
        title: 'Partition 3-2 and commit',
        domainId: 'raft',
        instruction: 'Run raft-split-brain-partition. Show which side can commit and prove the minority cannot.',
        hint: 'Majority math: which partition holds 3 of 5?',
        rubricItem: 'Proves only the majority partition commits, citing quorum overlap.',
      },
      {
        stepId: 'raft-log',
        title: 'Reconcile the logs',
        domainId: 'raft',
        instruction: 'Run raft-log-reconciliation after healing. Explain how the minority log converges without losing committed entries.',
        hint: 'Leader completeness: committed entries survive into every future leader.',
        rubricItem: 'Explains log matching + leader completeness preserving committed entries.',
      },
    ],
  },
  {
    id: 'dynamo-quorums',
    title: 'Dynamo-Style Quorums and Sloppy Failure Handling',
    question: 'Design read/write paths for a Dynamo-style store with N=3, targeting strong consistency with high availability.',
    topicTags: ['system-design', 'storage', 'backend'],
    timeLimitMinutes: 35,
    steps: [
      {
        stepId: 'db-quorum',
        title: 'Pick R and W',
        domainId: 'database',
        instruction: 'Open /database and configure replication. Choose R and W values and state the resulting guarantee.',
        hint: 'R + W > N is the whole game.',
        rubricItem: 'Selects R/W with a correct R+W>N overlap argument.',
      },
      {
        stepId: 'db-race',
        title: 'Break it, then fix it',
        domainId: 'database',
        instruction: 'Run db-quorum-race with W=1 to watch strong consistency fail, then restore a safe configuration.',
        hint: 'Read repair can mask staleness but not prevent it.',
        rubricItem: 'Demonstrates the failure mode and restores a provably safe quorum.',
      },
      {
        stepId: 'db-handoff',
        title: 'Handle a transient replica failure',
        domainId: 'database',
        instruction: 'Run db-hinted-handoff and explain what the hint stores, its TTL rationale, and what happens if the replica never returns.',
        hint: 'Hints are not replication — they expire.',
        rubricItem: 'Explains hinted handoff mechanics, TTL tradeoff, and permanent-failure fallback.',
      },
    ],
  },
  {
    id: 'kafka-acks-isr',
    title: 'Kafka Durability: acks, ISR, and min.insync.replicas',
    question: 'A team loses acknowledged writes on broker failover. Diagnose and fix their producer/topic configuration.',
    topicTags: ['streaming', 'backend'],
    timeLimitMinutes: 25,
    steps: [
      {
        stepId: 'kafka-isr',
        title: 'Inspect the ISR contract',
        domainId: 'kafka',
        instruction: 'Open /kafka and explain what ISR membership means and why it must be a replica subset.',
        hint: 'What does "in sync" mean for a broker with no log?',
        rubricItem: 'Defines ISR correctly and ties it to high-watermark advancement.',
      },
      {
        stepId: 'kafka-acks',
        title: 'Reproduce the loss',
        domainId: 'kafka',
        instruction: 'Configure acks=1 with min.insync.replicas=1, crash the leader, and show which acknowledged writes vanish and why.',
        hint: 'The follower that takes over never saw the write.',
        rubricItem: 'Reproduces the loss scenario and identifies the unsafe acks/ISR combination.',
      },
      {
        stepId: 'kafka-fix',
        title: 'Prescribe the fix',
        domainId: 'kafka',
        instruction: 'Set acks=-1 with min.insync.replicas=2 and argue the availability cost you just accepted.',
        hint: 'Durability and availability trade through the ISR size.',
        rubricItem: 'Prescribes a durable configuration and names its availability cost honestly.',
      },
    ],
  },
  {
    id: 'redis-failover',
    title: 'Redis Failover and Eviction Under Pressure',
    question: 'Design a Redis caching tier that survives master failover without stampedes or stale storms.',
    topicTags: ['caching', 'backend'],
    timeLimitMinutes: 30,
    steps: [
      {
        stepId: 'redis-failover',
        title: 'Fail over and measure staleness',
        domainId: 'redis',
        instruction: 'Run redis-master-failover and explain why the promoted replica serves stale reads.',
        hint: 'Async replication lag is the gap. What bounds it?',
        rubricItem: 'Explains async lag and names WAIT as the bounding mechanism.',
      },
      {
        stepId: 'redis-evict',
        title: 'Survive a scan flood',
        domainId: 'redis',
        instruction: 'Run redis-lru-lfu-shootout with a scan workload. Show which policy protects the hot set and why.',
        hint: 'One scan makes every cold key look "recent".',
        rubricItem: 'Demonstrates LFU resilience with the recency-pollution mechanism.',
      },
      {
        stepId: 'redis-slots',
        title: 'Move a slot without downtime',
        domainId: 'redis',
        instruction: 'Run redis-resharding-ask-moved and distinguish -ASK from -MOVED from the client’s perspective.',
        hint: 'Temporary redirect vs permanent map update.',
        rubricItem: 'Distinguishes ASK/MOVED and describes correct client handling of each.',
      },
    ],
  },
  {
    id: 'consistent-hashing-design',
    title: 'Consistent Hashing for a Growing Cache Fleet',
    question: 'Design key placement for a cache fleet that scales from 5 to 50 nodes with minimal data movement.',
    topicTags: ['system-design', 'algorithms', 'backend'],
    timeLimitMinutes: 25,
    steps: [
      {
        stepId: 'ch-ring',
        title: 'Place keys on the ring',
        domainId: 'consistent-hashing',
        instruction: 'Open /consistent-hashing, add nodes, and observe which keys move on each join.',
        hint: 'Only newly-owned ranges transfer.',
        rubricItem: 'States the ~1/N movement bound and demonstrates it.',
      },
      {
        stepId: 'ch-vnodes',
        title: 'Fix the imbalance',
        domainId: 'consistent-hashing',
        instruction: 'Show load imbalance with few virtual nodes, then raise the vnode count until the distribution converges.',
        hint: 'Random placement needs many samples to look uniform.',
        rubricItem: 'Demonstrates imbalance shrinking with vnode count and explains why.',
      },
      {
        stepId: 'ch-pick',
        title: 'Ring vs Jump vs Rendezvous',
        domainId: 'consistent-hashing',
        instruction: 'Argue which algorithm fits a 50-node cache fleet vs a 5-node metadata cluster, with lookup-cost reasoning.',
        hint: 'O(N) lookup is fine at N=5, fatal at scale.',
        rubricItem: 'Matches algorithm to cluster size with complexity and weighting arguments.',
      },
    ],
  },
];

export function interviewById(id: string): InterviewScript | undefined {
  return INTERVIEW_SCRIPTS.find((s) => s.id === id);
}
